Repository AlexsLemonade/OpenPBTA-manuscript, pull requests merged in 2022-03, with the labels that each got.

#180 add Run Jin, Shannon Robbins, update Krutika's email
  build/assets/custom-dictionary.txt
  content/metadata.yaml
Labels: ready for review

#190 WIP: add dois/key resource table updates
  content/06.methods.md
Labels: ready for review

#183 Update diagnosis info in methods
  build/assets/custom-dictionary.txt
  content/06.methods.md
Labels: ready for review

#194 update fig3 and S4 & results
  build/assets/custom-dictionary.txt
  content/03.results.md
  content/07.supplemental.md
  content/images/main/Figure3.png
  content/images/supplement/Figure-S4.png
  content/images/supplement/Figure-S5.png
Labels: ready for review

#202 update supp figures 1,2,5
  build/assets/custom-dictionary.txt
  content/03.results.md
  content/06.methods.md
  content/07.supplemental.md
  content/images/main/Figure5.png
  content/images/supplement/Figure-S1.pdf
  content/images/supplement/Figure-S1.png
Labels: ready for review

#216 add figure 1 legend
  content/03.results.md
  content/05.administrative.md
Labels: ready for review, merge next

#125 SNV-callers updating: TMB section
  content/06.methods.md
Labels: in progress, merge next

#199 update oncoprint Ns and figure legends
  build/assets/custom-dictionary.txt
  content/03.results.md
  content/07.supplemental.md
Labels: ready for review, merge next

#215 Add supp table descriptions to 07.supplemental.md
  content/03.results.md
  content/07.supplemental.md
Labels: ready for review

#223 KR table - critical commercial assays + TCGA
  build/assets/custom-dictionary.txt
  content/06.methods.md
Labels: merge next
